spring:
  main: 
    allow-bean-definition-overriding: true
    
server.port: 8090

dubbo:
  application:
    name: provider-service-app1
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer: 
    timeout: 3000

demo:
  service:
    version: 1.0.0