spring:
  main: 
    allow-bean-definition-overriding: true
    
server:
  port: 9091

dubbo:
  application:
    name: consumer-service-app1
    logger: slf4j

  registry:
    address: zookeeper://127.0.0.1:2181
  consumer: 
    timeout: 3000
  protocol:
      name: dubbo
      port: 20880

demo:
  service:
    version: 1.0.0
